version: "3.8"

services:
  table-reservations-service:
    container_name: table-reservations-container
    build: .
    image: table-reservations-image
    volumes:
      - ./:/app
    ports:
      - "8888:8888"


  jenkins-service:
    container_name: jenkins-container
    build: ./jenkins
    image: jenkins-image
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - table-reservations-service

volumes:
  jenkins_home: